### ISSUE TITLE
Resampling with list of patterns

### ISSUE THREAD

**Issue by zcapjdb** [umami-hep/umami-preprocessing#2] opened 2023-05-08 08:30 UTC
It was recently discovered that changes to the Sample class in ftag-tools caused a list of patterns to no longer be supported. This was fixed in [atlas-ftag-tools/#28](https://github.com/umami-hep/atlas-ftag-tools/pull/28). However it seems that things are still not 100% working as intended. When I start some resampling I can see that the correct number of jets are picked up (I think it's the correct amount as this is mc20+mc21 and the stats here are 2x the default of 40M):
```INFO     Estimated 93,247,500 lowpt_ttbar_cjets jets available - 80,000,000 requested```

However, the resampling eventually crashes like so:
```ValueError: Ran out of lowpt_ttbar_cjets jets after writing 40,192,067```

Which seems like it is reading all the cjets from the mc20 sample and then isn't looking into the mc21 samples I have provided in the config file:
```
ttbar: &ttbar
  name: ttbar
  pattern:
    - user.*.410470.*/*.h5
    - user.*.601230.*/*.h5
    - user.*.601229.*/*.h5
```

tagging @samvanstroud @AndriusVaitkus97

**Comment by samvanstroud** [comment] 2023-05-08 09:27
:( okay so it didn't quite get sorted. Would either of you @AndriusVaitkus97 @zcapjdb have time to investigate further? We should probably make a dedicated test (or four) case in the tools repo checking that this is really working as indended. For example generating multiple mock files, modifying the data in each so that it is identifiable, then making sure the reader is loading from the different files as expected

**Comment by AndriusVaitkus97** [comment] 2023-05-08 09:27
I'm actually looking into it now, while I have a bit of downtime

**Comment by AndriusVaitkus97** [comment] 2023-05-08 09:28
Sorry about that oversight!

**Comment by samvanstroud** [comment] 2023-05-08 09:31
No problem! thanks a lot for following up!!

**Comment by AndriusVaitkus97** [comment] 2023-05-09 15:38
Only took me a day and a half, but I think I found the bug!

Basically what was happening, is that when each file was being read (in parallel, in batches), if they did not have the same total jets, then the shorter one finishing would cause all streams to end.

I fixed this on my fork [in this commit](https://github.com/AndriusVaitkus97/atlas-ftag-tools/commit/f78bec7af4c531e616a90b95425d6d083d9f7430). I have not had time to even think about tests yet, but please let me know if this looks right @samvanstroud.

**Comment by samvanstroud** [comment] 2023-05-09 16:23
> Only took me a day and a half, but I think I found the bug!
> 
> Basically what was happening, is that when each file was being read (in parallel, in batches), if they did not have the same total jets, then the shorter one finishing would cause all streams to end.
> 
> I fixed this on my fork [in this commit](https://github.com/AndriusVaitkus97/atlas-ftag-tools/commit/f78bec7af4c531e616a90b95425d6d083d9f7430). I have not had time to even think about tests yet, but please let me know if this looks right @samvanstroud.

hmm, I'm not sure, that was the intended behaviour since for each batch we should load jets from the all the different samples and combine them, the idea was that if one of your streams runs out you can no longer combine things in the way that you need to, so you have to stop all of them.

I might be helpful to first define some tests, then we can check this fix against them.

**Comment by samvanstroud** [comment] 2023-07-17 13:19
@AndriusVaitkus97 @zcapjdb -- I guess we can close this

**Closed by samvanstroud** 2023-07-17 13:19 UTC
